# Start the server on port 8080
server.port=8080

# Configure the H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:hoteldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable the web console so you can look at the database in your browser!
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Camunda API configuration
camunda.client.mode=saas
camunda.client.auth.client-id=.agQXvDfaKTQYEUcr42t4lAOhSpYJ~T9
camunda.client.auth.client-secret=GH_z0rbfs5HuYJuUnOq2KKoxqP6VkNrm_YPA8jyhmlNJ2RdIvdcx7bju~kwQ3TaS
camunda.client.cloud.cluster-id=3f91263a-a4b1-42b0-89ef-ce100800d56e
camunda.client.cloud.region=fra-1

# Apache Camel Configuration
camel.springboot.auto-startup=true
camel.springboot.jmx-enabled=true
camel.springboot.context-name=holmesHotelCamelContext
camel.servlet.mapping.context-path=/camel/api/*
camel.rest.api-docs.enabled=true
camel.rest.api-docs.title=Holmes Hotel Camel API
camel.rest.api-docs.description=Omnichannel Gateway for Booking, Service Orders, and Complaints
camel.rest.api-docs.version=1.0.0

# Logging
logging.level.org.apache.camel=INFO
logging.level.com.holmeshotel=DEBUG